version: "3.8"
services:

  envoy:
    image: envoyproxy/envoy:v1.25.2
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/jwks.json:/etc/envoy/jwks.json
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster envoy --service-node envoy
    ports:
      - 9099:9099

  application:
    container_name: app
    image: envoytokengenerator:latest
    build:
      context: ./application
    volumes:
      - ./application/private.key:/app/private.key
      - ./application/public.key:/app/public.key
    environment:
      CONNECTION_STRING: root:rootjwt-app123@tcp(mariadb_db:3306)/jwt-app?parseTime=true
      PORT: ":80"
      ACCESS_TOKEN_MAX_AGE: 10
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb_db
    environment:
      - MYSQL_DATABASE=jwt-app
      - MYSQL_USER=jwt-app
      - MYSQL_PASSWORD=jwt-app123
      - MYSQL_ROOT_PASSWORD=rootjwt-app123
    restart: unless-stopped
    image: mariadb:latest
    volumes:
      - ./dbdata:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

